Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 0
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  DefaultContextTimeout: 60 * 1000 * 1000 * 1000
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
      - .jpg
      - .jpeg
      - .png
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:3306
  DBName: movie
  TablePrefix:
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Network: tcp
  Server: 127.0.0.1:6379
  Password:
  DB: 0
JWT:
  AccessSecret: MPL2Vv!6qin1ZI&E
  RefreshSecret: Q(Y$A43T9q&)ERLrc
  Issuer: CONGA1FX0
  AtExpires: 900
  RtExpires: 604800