package errcode

var (
	Success                   = NewError(200, "success")
	ServerError               = NewError(1000, "server error")
	InvalidParams             = NewError(1001, "invalid params")
	NotFound                  = NewError(1002, "not found")
	UnauthorizedAuthNotExist  = NewError(1003, "auth not exist")
	UnauthorizedTokenError    = NewError(1004, "token error")
	UnauthorizedTokenTimeout  = NewError(1005, "token expires")
	UnauthorizedTokenGenerate = NewError(1006, "generate token failed")
	TooManyRequests           = NewError(1007, "too many requests")
	IsSignup                  = NewError(1008, "is signup")
	NotSignup                 = NewError(1009, "not signup")
	ErrorUploadFileFail       = NewError(1010, "failed to upload")
	RecordNotFound            = NewError(1011, "record not found")
	CaptchaError              = NewError(1012, "captcha error")
	Forbidden                 = NewError(1013, "forbidden")
	Sold                      = NewError(1014, "seat sold")
)
